import type { Component } from 'vue'
import {
  Activity,
  AppWindow,
  Archive,
  BadgeCheck,
  BadgeDollarSign,
  BadgeInfo,
  Bell,
  Binary,
  Blocks,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Boxes,
  BrainCircuit,
  Braces,
  BriefcaseBusiness,
  Bug,
  Building2,
  Cable,
  CalendarDays,
  ChartBarBig,
  ChartLine,
  ChartNetwork,
  ChartNoAxesCombined,
  ChartPie,
  CircleGauge,
  CircleQuestionMark,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudUpload,
  CodeXml,
  Cog,
  Contact,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Eye,
  File,
  FileCode,
  Files,
  FileText,
  FingerprintPattern,
  Flag,
  FlaskConical,
  Folder,
  FolderKanban,
  FolderOpen,
  Funnel,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitMerge,
  GitPullRequest,
  Hammer,
  HardDrive,
  Headphones,
  House,
  Image,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  ListTree,
  LockKeyhole,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  MessagesSquare,
  Microchip,
  MonitorCog,
  Network,
  NotebookPen,
  Package,
  PanelLeft,
  PanelsTopLeft,
  Paperclip,
  Phone,
  Puzzle,
  Receipt,
  RefreshCw,
  Repeat2,
  Rocket,
  Route,
  ScanFace,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Sheet,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  SquareTerminal,
  Star,
  Store,
  Table2,
  Tags,
  Target,
  Terminal,
  TestTubes,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCog,
  UserKey,
  UserLock,
  UserRoundCheck,
  Users,
  Video,
  Wallet,
  WandSparkles,
  Webhook,
  Workflow,
  Wrench,
} from '@lucide/vue'

export type MenuIconCategory =
  | 'general'
  | 'business'
  | 'ai'
  | 'development'
  | 'data'
  | 'security'
  | 'communication'
  | 'files'
  | 'system'

export interface MenuIconOption {
  value: string
  label: string
  component: Component
  category: MenuIconCategory
  keywords?: string
}

export const menuIconCategories: Array<{
  value: 'all' | MenuIconCategory
  label: string
}> = [
  { value: 'all', label: '全部' },
  { value: 'general', label: '通用' },
  { value: 'business', label: '业务' },
  { value: 'ai', label: 'AI' },
  { value: 'development', label: '开发' },
  { value: 'data', label: '数据' },
  { value: 'security', label: '安全' },
  { value: 'communication', label: '沟通' },
  { value: 'files', label: '文件' },
  { value: 'system', label: '系统' },
]

export const menuIconOptions: MenuIconOption[] = [
  {
    value: 'lucide:layout-dashboard',
    label: '仪表盘',
    component: LayoutDashboard,
    category: 'general',
  },
  { value: 'lucide:house', label: '首页', component: House, category: 'general' },
  { value: 'lucide:app-window', label: '应用窗口', component: AppWindow, category: 'general' },
  { value: 'lucide:layout-grid', label: '应用网格', component: LayoutGrid, category: 'general' },
  {
    value: 'lucide:panels-top-left',
    label: '页面布局',
    component: PanelsTopLeft,
    category: 'general',
  },
  { value: 'lucide:panel-left', label: '侧边栏', component: PanelLeft, category: 'general' },
  { value: 'lucide:menu', label: '菜单', component: Menu, category: 'general' },
  {
    value: 'lucide:folder-kanban',
    label: '项目管理',
    component: FolderKanban,
    category: 'general',
  },
  { value: 'lucide:calendar-days', label: '日历', component: CalendarDays, category: 'general' },
  { value: 'lucide:clock', label: '时间', component: Clock, category: 'general' },
  { value: 'lucide:map-pin', label: '位置', component: MapPin, category: 'general' },
  { value: 'lucide:star', label: '收藏', component: Star, category: 'general' },
  { value: 'lucide:bookmark', label: '书签', component: Bookmark, category: 'general' },
  { value: 'lucide:tags', label: '标签', component: Tags, category: 'general' },
  { value: 'lucide:flag', label: '标记', component: Flag, category: 'general' },
  { value: 'lucide:target', label: '目标', component: Target, category: 'general' },

  {
    value: 'lucide:briefcase-business',
    label: '业务管理',
    component: BriefcaseBusiness,
    category: 'business',
  },
  { value: 'lucide:building-2', label: '企业', component: Building2, category: 'business' },
  { value: 'lucide:store', label: '商店', component: Store, category: 'business' },
  { value: 'lucide:shopping-cart', label: '购物车', component: ShoppingCart, category: 'business' },
  { value: 'lucide:package', label: '商品', component: Package, category: 'business' },
  { value: 'lucide:boxes', label: '库存', component: Boxes, category: 'business' },
  { value: 'lucide:truck', label: '物流', component: Truck, category: 'business' },
  { value: 'lucide:wallet', label: '钱包', component: Wallet, category: 'business' },
  { value: 'lucide:credit-card', label: '支付', component: CreditCard, category: 'business' },
  { value: 'lucide:receipt', label: '账单', component: Receipt, category: 'business' },
  {
    value: 'lucide:badge-dollar-sign',
    label: '计费',
    component: BadgeDollarSign,
    category: 'business',
  },
  { value: 'lucide:dollar-sign', label: '金额', component: DollarSign, category: 'business' },
  { value: 'lucide:contact', label: '客户', component: Contact, category: 'business' },

  { value: 'lucide:bot', label: '机器人', component: Bot, category: 'ai' },
  { value: 'lucide:brain-circuit', label: 'AI 智能', component: BrainCircuit, category: 'ai' },
  { value: 'lucide:sparkles', label: '智能生成', component: Sparkles, category: 'ai' },
  { value: 'lucide:wand-sparkles', label: '智能助手', component: WandSparkles, category: 'ai' },
  { value: 'lucide:cpu', label: '计算核心', component: Cpu, category: 'ai' },
  { value: 'lucide:microchip', label: '芯片', component: Microchip, category: 'ai' },
  { value: 'lucide:binary', label: '机器数据', component: Binary, category: 'ai' },
  { value: 'lucide:rocket', label: '快速启动', component: Rocket, category: 'ai' },
  { value: 'lucide:blocks', label: '能力模块', component: Blocks, category: 'ai' },
  { value: 'lucide:puzzle', label: '智能插件', component: Puzzle, category: 'ai' },

  { value: 'lucide:code-xml', label: '代码', component: CodeXml, category: 'development' },
  { value: 'lucide:braces', label: '源码', component: Braces, category: 'development' },
  { value: 'lucide:file-code', label: '代码文件', component: FileCode, category: 'development' },
  { value: 'lucide:terminal', label: '命令行', component: Terminal, category: 'development' },
  {
    value: 'lucide:square-terminal',
    label: '终端',
    component: SquareTerminal,
    category: 'development',
  },
  { value: 'lucide:git-branch', label: '代码分支', component: GitBranch, category: 'development' },
  {
    value: 'lucide:git-commit-horizontal',
    label: '代码提交',
    component: GitCommitHorizontal,
    category: 'development',
  },
  {
    value: 'lucide:git-pull-request',
    label: '代码评审',
    component: GitPullRequest,
    category: 'development',
  },
  { value: 'lucide:git-merge', label: '代码合并', component: GitMerge, category: 'development' },
  { value: 'lucide:git-fork', label: '代码派生', component: GitFork, category: 'development' },
  { value: 'lucide:webhook', label: 'WebHook', component: Webhook, category: 'development' },
  { value: 'lucide:workflow', label: '工作流', component: Workflow, category: 'development' },
  { value: 'lucide:bug', label: '缺陷', component: Bug, category: 'development' },
  {
    value: 'lucide:flask-conical',
    label: '实验',
    component: FlaskConical,
    category: 'development',
  },
  { value: 'lucide:test-tubes', label: '测试', component: TestTubes, category: 'development' },

  { value: 'lucide:database', label: '数据库', component: Database, category: 'data' },
  { value: 'lucide:hard-drive', label: '存储', component: HardDrive, category: 'data' },
  { value: 'lucide:server', label: '服务器', component: Server, category: 'data' },
  { value: 'lucide:cloud', label: '云服务', component: Cloud, category: 'data' },
  { value: 'lucide:cloud-cog', label: '云配置', component: CloudCog, category: 'data' },
  { value: 'lucide:cloud-upload', label: '云上传', component: CloudUpload, category: 'data' },
  { value: 'lucide:cloud-download', label: '云下载', component: CloudDownload, category: 'data' },
  {
    value: 'lucide:chart-no-axes-combined',
    label: '数据分析',
    component: ChartNoAxesCombined,
    category: 'data',
  },
  { value: 'lucide:chart-bar-big', label: '柱状图', component: ChartBarBig, category: 'data' },
  { value: 'lucide:chart-line', label: '趋势图', component: ChartLine, category: 'data' },
  { value: 'lucide:chart-pie', label: '饼图', component: ChartPie, category: 'data' },
  { value: 'lucide:chart-network', label: '关系图', component: ChartNetwork, category: 'data' },
  { value: 'lucide:trending-up', label: '增长趋势', component: TrendingUp, category: 'data' },
  { value: 'lucide:table-2', label: '数据表', component: Table2, category: 'data' },
  { value: 'lucide:sheet', label: '表格', component: Sheet, category: 'data' },
  { value: 'lucide:funnel', label: '筛选', component: Funnel, category: 'data' },
  { value: 'lucide:search', label: '搜索', component: Search, category: 'data' },
  { value: 'lucide:scan-search', label: '扫描查询', component: ScanSearch, category: 'data' },
  { value: 'lucide:gauge', label: '指标', component: Gauge, category: 'data' },
  { value: 'lucide:circle-gauge', label: '监控', component: CircleGauge, category: 'data' },
  { value: 'lucide:activity', label: '活动', component: Activity, category: 'data' },

  { value: 'lucide:shield', label: '权限', component: Shield, category: 'security' },
  { value: 'lucide:shield-check', label: '安全检查', component: ShieldCheck, category: 'security' },
  { value: 'lucide:shield-alert', label: '安全告警', component: ShieldAlert, category: 'security' },
  { value: 'lucide:lock-keyhole', label: '安全锁', component: LockKeyhole, category: 'security' },
  { value: 'lucide:key-round', label: '密钥', component: KeyRound, category: 'security' },
  {
    value: 'lucide:fingerprint-pattern',
    label: '指纹识别',
    component: FingerprintPattern,
    category: 'security',
  },
  { value: 'lucide:scan-face', label: '身份识别', component: ScanFace, category: 'security' },
  { value: 'lucide:user-key', label: '用户授权', component: UserKey, category: 'security' },
  { value: 'lucide:user-lock', label: '用户锁定', component: UserLock, category: 'security' },
  { value: 'lucide:eye', label: '可见性', component: Eye, category: 'security' },
  { value: 'lucide:badge-check', label: '认证', component: BadgeCheck, category: 'security' },

  { value: 'lucide:bell', label: '通知', component: Bell, category: 'communication' },
  { value: 'lucide:mail', label: '邮件', component: Mail, category: 'communication' },
  {
    value: 'lucide:message-square',
    label: '消息',
    component: MessageSquare,
    category: 'communication',
  },
  {
    value: 'lucide:messages-square',
    label: '会话',
    component: MessagesSquare,
    category: 'communication',
  },
  { value: 'lucide:send', label: '发送', component: Send, category: 'communication' },
  { value: 'lucide:phone', label: '电话', component: Phone, category: 'communication' },
  { value: 'lucide:video', label: '视频', component: Video, category: 'communication' },
  { value: 'lucide:megaphone', label: '公告', component: Megaphone, category: 'communication' },
  { value: 'lucide:headphones', label: '客服', component: Headphones, category: 'communication' },
  {
    value: 'lucide:circle-help',
    label: '帮助',
    component: CircleQuestionMark,
    category: 'communication',
  },
  { value: 'lucide:badge-info', label: '信息', component: BadgeInfo, category: 'communication' },

  { value: 'lucide:folder', label: '目录', component: Folder, category: 'files' },
  { value: 'lucide:folder-open', label: '打开目录', component: FolderOpen, category: 'files' },
  { value: 'lucide:file', label: '文件', component: File, category: 'files' },
  { value: 'lucide:files', label: '文件集合', component: Files, category: 'files' },
  { value: 'lucide:file-text', label: '文档', component: FileText, category: 'files' },
  { value: 'lucide:archive', label: '归档', component: Archive, category: 'files' },
  { value: 'lucide:book-open', label: '知识库', component: BookOpen, category: 'files' },
  { value: 'lucide:book-marked', label: '手册', component: BookMarked, category: 'files' },
  { value: 'lucide:clipboard-list', label: '清单', component: ClipboardList, category: 'files' },
  {
    value: 'lucide:clipboard-check',
    label: '检查单',
    component: ClipboardCheck,
    category: 'files',
  },
  { value: 'lucide:notebook-pen', label: '笔记', component: NotebookPen, category: 'files' },
  { value: 'lucide:image', label: '图片', component: Image, category: 'files' },
  { value: 'lucide:paperclip', label: '附件', component: Paperclip, category: 'files' },
  { value: 'lucide:upload', label: '上传', component: Upload, category: 'files' },
  { value: 'lucide:download', label: '下载', component: Download, category: 'files' },

  { value: 'lucide:settings', label: '设置', component: Settings, category: 'system' },
  { value: 'lucide:cog', label: '系统配置', component: Cog, category: 'system' },
  { value: 'lucide:monitor-cog', label: '节点管理', component: MonitorCog, category: 'system' },
  {
    value: 'lucide:sliders-horizontal',
    label: '参数配置',
    component: SlidersHorizontal,
    category: 'system',
  },
  { value: 'lucide:wrench', label: '工具', component: Wrench, category: 'system' },
  { value: 'lucide:hammer', label: '维护', component: Hammer, category: 'system' },
  { value: 'lucide:cable', label: '连接', component: Cable, category: 'system' },
  { value: 'lucide:network', label: '网络', component: Network, category: 'system' },
  { value: 'lucide:route', label: '路由', component: Route, category: 'system' },
  { value: 'lucide:refresh-cw', label: '刷新', component: RefreshCw, category: 'system' },
  { value: 'lucide:repeat-2', label: '同步', component: Repeat2, category: 'system' },
  { value: 'lucide:list-tree', label: '菜单树', component: ListTree, category: 'system' },
  { value: 'lucide:list-checks', label: '任务列表', component: ListChecks, category: 'system' },
  { value: 'lucide:user', label: '用户', component: User, category: 'system' },
  { value: 'lucide:users', label: '用户组', component: Users, category: 'system' },
  { value: 'lucide:user-cog', label: '账户设置', component: UserCog, category: 'system' },
  {
    value: 'lucide:user-round-check',
    label: '用户审核',
    component: UserRoundCheck,
    category: 'system',
  },
]

const iconComponents = new Map(menuIconOptions.map((option) => [option.value, option.component]))
const iconAliases = new Map(
  menuIconOptions.flatMap((option) => {
    const name = option.value.slice('lucide:'.length)
    return [
      [name, option.value],
      [name.replaceAll('-', ''), option.value],
    ] as Array<[string, string]>
  }),
)

export function normalizeMenuIcon(icon?: string): string {
  const value = icon?.trim().toLowerCase()
  if (!value) return ''
  if (iconComponents.has(value)) return value

  const lucideName = value.startsWith('lucide:') ? value.slice('lucide:'.length) : value
  return iconAliases.get(lucideName) || iconAliases.get(lucideName.replaceAll('-', '')) || value
}

export function resolveMenuIcon(icon?: string): Component | undefined {
  return iconComponents.get(normalizeMenuIcon(icon))
}
